# Site settings
title: Evren DOĞAN
description: 'Evren DOĞAN - Kişisel Bloğu'
url: 'https://evrend.github.io/'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Evren Doğan'
  email: evrend@outlook.com
#  twitter_username: joshgerdes
  facebook_username: evrenndogan
  github_username:  evrend
  linkedin_username:  evrendogan

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
